import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import requests from '../utils/requests'


export default function Home({ results }) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.co" />
      </Head>

      <Header />

      <Navbar />

      <Results results={results}/>

    </div>
  )
}


export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => res.json())
 

// this is letting me use the props of the api results i got from the fetch 
  return {
    props: {
      results: request.results,
    },
  }



}
